﻿/*----------------------------------
 *Title:UI自动化组件生成代码生成工具
 *Date:2026/2/1 17:26:52
 *Description:变量需要以[Text]括号加组件类型的格式进行声明,然后右键窗口物体——一键生成UI数据组件脚本即可
 *注意:自动生成的内容仅追加/移除，不会覆盖手写逻辑；新增/删除组件后再次生成，会标记对应代码行
----------------------------------*/
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;
using TMPro;
using DG.Tweening;
using System.Collections;

namespace KNXL.AutoGenerated.UI
{

	public class EndPanel:BasePanel
	{
		//字段声明
		public Button btnNext;
		public Text txtNext;
		// 留给新增的字段
		//自己手写的字段声明，不会被覆盖
		int clickCount = 0;
		[SerializeField]
		private GameObject[] objs;
		[SerializeField]
		private CanvasGroup canvasGroup;
		// 动画播放状态标记
		private bool isAnimating = false;
		public Ease easeType = Ease.InBack;

		//重写Awake方法
		protected override void Awake()
		{
			base.Awake();
			//自己手写的Awake逻辑，不会被覆盖
		}

		//重写Start方法,完成事件绑定
		protected override void Start()
		{
			base.Start();
			//组件事件绑定
			btnNext.onClick.AddListener(()=>OnbtnNextButtonClick());
			// 留给新增的组件事件绑定
			//自己手写的Start逻辑，不会被覆盖
			MusicMgr.Instance.PlayBKMusic(40004);
		}

		public override void ShowMe(UnityAction callback = null)
		{
			//执行父类的ShowMe方法
			base.ShowMe(callback);
			//自己手写的ShowMe逻辑，不会被覆盖
		}

		public override void HideMe(UnityAction callback = null)
		{
			//执行父类的HideMe方法
			base.HideMe(callback);
			//自己手写的HideMe逻辑，不会被覆盖
		}

		private void OnbtnNextButtonClick()
		{
			MusicMgr.Instance.PlaySound("摁键选项");
			if(clickCount >= objs.Length)
            {
                // 点击任意键返回主菜单
				UIMgr.Instance.HidePanel<GameUIPanel>();
				
                UIMgr.Instance.ShowPanel<FaderPanel>(callBack: (panel) =>
				{
					SceneMgr.Instance.LoadSceneAsyn(Setting.START_SCENE_NAME, () => FadeOutStartScene(panel), () => FadeInGameScene(panel));
				});
                // SceneMgr.Instance.LoadScene(Setting.START_SCENE_NAME);
				
                return;
            }
			else
            {
                // 如果动画正在播放，则不响应点击
                if (isAnimating)
                    return;
                    
                PlayImageAnim(clickCount);
            }
			
		}

		// 留给新增的组件事件绑定函数
		// 自己写的内容

		private void PlayImageAnim(int index)
		{
			// 设置动画播放状态为true
			isAnimating = true;
			
			GameObject obj = objs[index];
			if(index == 0)
            {
                obj.transform.localPosition = new Vector3(-182,2000,0);
				DOTween.To(()=>obj.transform.localPosition,x=>obj.transform.localPosition=x,new Vector3(-182,392,0),0.5f)
				.SetEase(easeType)
				.OnComplete(() => OnAnimComplete());
            }
			else if(index == 1)
            {
                obj.transform.localPosition = new Vector3(236,2000,0);
				DOTween.To(()=>obj.transform.localPosition,x=>obj.transform.localPosition=x,new Vector3(236,392,0),0.5f)
				.SetEase(easeType)
				.OnComplete(() => OnAnimComplete());
            }
			else if(index == 2)
            {
                obj.transform.localPosition = new Vector3(-2000,88,0);
				DOTween.To(()=>obj.transform.localPosition,x=>obj.transform.localPosition=x,new Vector3(-247,88,0),0.5f)
				.SetEase(easeType)
				.OnComplete(() => OnAnimComplete());
            }
			else if(index == 3)
            {
                obj.transform.localPosition = new Vector3(2000,88,0);
				DOTween.To(()=>obj.transform.localPosition,x=>obj.transform.localPosition=x,new Vector3(115,88,0),0.5f)
				.SetEase(easeType)
				.OnComplete(() => OnAnimComplete());
            }
			else if(index == 4)
            {
                obj.transform.localPosition = new Vector3(-61,-2000,0);
				DOTween.To(()=>obj.transform.localPosition,x=>obj.transform.localPosition=x,new Vector3(-61,-312,0),0.5f)
				.SetEase(easeType)
				.OnComplete(() => OnAnimComplete());
            }
			else if(index == 5)
            {
                obj.transform.localPosition = new Vector3(-2000,-131,0);
				DOTween.To(()=>obj.transform.localPosition,x=>obj.transform.localPosition=x,new Vector3(-665,-131,0),0.5f)
				.SetEase(easeType)
				.OnComplete(() => OnAnimComplete());
            }
			else if(index == 6)
            {
				DOTween.To(()=>canvasGroup.alpha,x=>canvasGroup.alpha=x,1,2f)
				.SetEase(easeType)
				.OnComplete(() => OnAnimComplete());
            }
		}
		
		// 动画完成回调
		private void OnAnimComplete()
		{
			// 动画播放完成，更新状态
			isAnimating = false;
			
			// 增加点击计数
			clickCount++;
			
			// 检查是否所有动画都已播放完毕
			if(clickCount >= objs.Length)
			{
				txtNext.text = "任意点击返回主菜单...";
			}
		}
	
		/// <summary>
		/// 淡出开始场景
		/// </summary>
		/// <param name="panel"></param>
		/// <returns></returns>
		private IEnumerator FadeOutStartScene(FaderPanel panel)
		{
			yield return panel.FadeIn(1);
			UIMgr.Instance.HidePanel<EndPanel>();
		}

		private IEnumerator FadeInGameScene(FaderPanel panel)
		{
			MusicMgr.Instance.PlayBKMusic(40001);
			UIMgr.Instance.ShowPanel<GameStartPanel>();
			yield return panel.FadeOut(1);
		}
	}
}