﻿/*----------------------------------
 *Title:UI自动化组件生成代码生成工具
 *Date:2026/2/1 22:04:34
 *Description:变量需要以[Text]括号加组件类型的格式进行声明,然后右键窗口物体——一键生成UI数据组件脚本即可
 *注意:自动生成的内容仅追加/移除，不会覆盖手写逻辑；新增/删除组件后再次生成，会标记对应代码行
----------------------------------*/
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;
using TMPro;
using System.Collections;

namespace KNXL.AutoGenerated.UI
{

	public class FaderPanel : BasePanel
	{
		//字段声明
		// 留给新增的字段
		//自己手写的字段声明，不会被覆盖
		private CanvasGroup canvasGroup;

		//重写Awake方法
		protected override void Awake()
		{
			base.Awake();
			//自己手写的Awake逻辑，不会被覆盖
			canvasGroup = GetComponent<CanvasGroup>();
		}

		//重写Start方法,完成事件绑定
		protected override void Start()
		{
			base.Start();
			//组件事件绑定
			// 留给新增的组件事件绑定
			//自己手写的Start逻辑，不会被覆盖
			// 初始设置透明度为0
			canvasGroup.alpha = 0;
		}

		public override void ShowMe(UnityAction callback = null)
		{
			//执行父类的ShowMe方法
			base.ShowMe(callback);
			//自己手写的ShowMe逻辑，不会被覆盖
			// 默认调用淡入效果
			FadeIn(1f, callback);
		}


		public override void HideMe(UnityAction callback = null)
		{
			//执行父类的HideMe方法
			// 不立即执行父类的HideMe，而是在淡出完成后执行
			//base.HideMe(callback);
			//自己手写的HideMe逻辑，不会被覆盖
			// 默认调用淡出效果，淡出后执行父类的HideMe
			FadeOut(1f, true, () =>
			{
				base.HideMe(callback);
			});
		}

		// 留给新增的组件事件绑定函数
		//自己写的内容

		/// <summary>
		/// 淡入效果
		/// </summary>
		/// <param name="duration">淡入持续时间</param>
		/// <param name="callback">淡入完成后的回调函数</param>
		public IEnumerator FadeIn(float duration = 1f, UnityAction callback = null)
		{
			// 开始淡入协程
			yield return FadeInCoroutine(duration, callback);
		}

		/// <summary>
		/// 淡出效果
		/// </summary>
		/// <param name="duration">淡出持续时间</param>
		/// <param name="hideAfterFade">淡出后是否隐藏面板</param>
		/// <param name="callback">淡出完成后的回调函数</param>
		public IEnumerator FadeOut(float duration = 1f, bool hideAfterFade = true, UnityAction callback = null)
		{
			// 开始淡出协程
			yield return FadeOutCoroutine(duration, hideAfterFade, callback);
		}

		/// <summary>
		/// 淡入协程
		/// </summary>
		private System.Collections.IEnumerator FadeInCoroutine(float duration, UnityAction callback)
		{
			// 设置初始透明度为0
			canvasGroup.alpha = 0;
			// 启用交互
			canvasGroup.interactable = true;
			canvasGroup.blocksRaycasts = true;

			float elapsedTime = 0f;
			// 平滑增加透明度
			while (elapsedTime < duration)
			{
				canvasGroup.alpha = Mathf.Lerp(0, 1, elapsedTime / duration);
				elapsedTime += Time.deltaTime;
				yield return null;
			}

			// 确保最终透明度为1
			canvasGroup.alpha = 1;
			// 调用回调函数
			callback?.Invoke();
		}

		/// <summary>
		/// 淡出协程
		/// </summary>
		private System.Collections.IEnumerator FadeOutCoroutine(float duration, bool hideAfterFade, UnityAction callback)
		{
			// 设置初始透明度为1
			canvasGroup.alpha = 1;

			float elapsedTime = 0f;
			// 平滑减少透明度
			while (elapsedTime < duration)
			{
				canvasGroup.alpha = Mathf.Lerp(1, 0, elapsedTime / duration);
				elapsedTime += Time.deltaTime;
				yield return null;
			}

			// 确保最终透明度为0
			canvasGroup.alpha = 0;
			// 禁用交互
			canvasGroup.interactable = false;
			canvasGroup.blocksRaycasts = false;

			// 如果需要，隐藏面板
			if (hideAfterFade)
			{
				gameObject.SetActive(false);
			}

			// 调用回调函数
			callback?.Invoke();
		}
	}
}