/*----------------------------------
 *Title:UI自动化组件生成代码生成工具
 *Date:2026/2/1 16:55:24
 *Description:变量需要以[Text]括号加组件类型的格式进行声明,然后右键窗口物体——一键生成UI数据组件脚本即可
 *注意:自动生成的内容仅追加/移除，不会覆盖手写逻辑；新增/删除组件后再次生成，会标记对应代码行
----------------------------------*/
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;
using TMPro;

namespace KNXL.AutoGenerated.UI
{

	public class GameOverPanel:BasePanel
	{
		//字段声明
		public Button Restart;
		// 留给新增的字段
		public Button Again;
		//自己手写的字段声明，不会被覆盖

		//重写Awake方法
		protected override void Awake()
		{
			base.Awake();
			//自己手写的Awake逻辑，不会被覆盖
		}

		//重写Start方法,完成事件绑定
		protected override void Start()
		{
			base.Start();
			//组件事件绑定
			Restart.onClick.AddListener(()=>OnRestartButtonClick());
			// 留给新增的组件事件绑定
			Again.onClick.AddListener(()=>OnAgainButtonClick());
			//自己手写的Start逻辑，不会被覆盖
			MusicMgr.Instance.PlaySound(40014);
		}

		public override void ShowMe(UnityAction callback = null)
		{
			//执行父类的ShowMe方法
			base.ShowMe(callback);
			//自己手写的ShowMe逻辑，不会被覆盖
		}

		public override void HideMe(UnityAction callback = null)
		{
			//执行父类的HideMe方法
			base.HideMe(callback);
			//自己手写的HideMe逻辑，不会被覆盖
			// 重置游戏结束面板显示标志
			Player.ResetGameOverPanelShown();
		}

		private void OnRestartButtonClick()
		{
			MusicMgr.Instance.PlaySound("摁键选项");
			UIMgr.Instance.HidePanel<GameOverPanel>();
			GameManager.Instance.LoadGame();
			GameManager.Instance.GameLogic.GenerateLevel(GameManager.Instance.CurrentLevel);
			GameManager.Instance.InitPlayer();
		}

		// 留给新增的组件事件绑定函数
		private void OnAgainButtonClick()
		{
			MusicMgr.Instance.PlaySound("摁键选项");
			UIMgr.Instance.HidePanel<GameOverPanel>();
			GameManager.Instance.GoToFirstLevel();
			GameManager.Instance.GameLogic.GenerateLevel(GameManager.Instance.CurrentLevel);
			GameManager.Instance.InitPlayer();
		}
		//自己写的内容
	}
}