﻿/*----------------------------------
*Title:UI自动化组件生成代码生成工具
*Date:2026/2/1 18:27:46
*Description:变量需要以[Text]括号加组件类型的格式进行声明,然后右键窗口物体——一键生成UI数据组件脚本即可
*注意:自动生成的内容仅追加/移除，不会覆盖手写逻辑；新增/删除组件后再次生成，会标记对应代码行
----------------------------------*/
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;
using TMPro;

namespace KNXL.AutoGenerated.UI
{

    public class GameUIPanel : BasePanel
    {
        //字段声明
        public Image mianju;
        public TextMeshProUGUI tmpValue;
        public Button Pause;
        // 留给新增的字段
        //自己手写的字段声明，不会被覆盖
        // 动画状态标记和当前协程引用
        private bool isAnimating = false;
        private System.Collections.IEnumerator currentAnimationCoroutine;
        public Color color1;
        public Color color2;
        public Color color3;

        //重写Awake方法
        protected override void Awake()
        {
            base.Awake();
            //自己手写的Awake逻辑，不会被覆盖
        }

        //重写Start方法,完成事件绑定
        protected override void Start()
        {
            base.Start();
            //组件事件绑定
            Pause.onClick.AddListener(() => OnPauseButtonClick());
            // 留给新增的组件事件绑定
            //自己手写的Start逻辑，不会被覆盖
        }

        public override void ShowMe(UnityAction callback = null)
        {
            //执行父类的ShowMe方法
            base.ShowMe(callback);
            //自己手写的ShowMe逻辑，不会被覆盖
        }

        public override void HideMe(UnityAction callback = null)
        {
            //执行父类的HideMe方法
            base.HideMe(callback);
            //自己手写的HideMe逻辑，不会被覆盖
        }

        private void OnPauseButtonClick()
        {
            MusicMgr.Instance.PlaySound("摁键选项");
            UIMgr.Instance.ShowPanel<PausePanel>(showAnimType: E_ShowAnimType.SlideInFromLeft);
        }

        // 留给新增的组件事件绑定函数
        //自己写的内容
        public void UpdateValue(int value)
        {
            if (value <= 3)
            {
                tmpValue.color = color3;
                mianju.color = color3;
            }
            else if (value <= 6)
            {
                tmpValue.color = color2;
                mianju.color = color2;
            }
            else
            {
                tmpValue.color = color1;
                mianju.color = color1;
            }
            tmpValue.text = value.ToString();
            Vector2 startPos = new Vector2(50, -550);
            Vector2 endPos = new Vector2(50, 150);

            // 根据value计算目标位置
            Vector2 targetPos = Vector2.Lerp(startPos, endPos, value / 10f);

            // 如果有动画正在执行，先停止它
            if (isAnimating)
            {
                StopCoroutine(currentAnimationCoroutine);
                isAnimating = false;
            }

            // 启动新的动画协程
            currentAnimationCoroutine = SmoothMoveToPosition(targetPos, 0.5f);
            StartCoroutine(currentAnimationCoroutine);
        }

        /// <summary>
        /// 平滑移动到目标位置的协程
        /// </summary>
        /// <param name="targetPos">目标位置</param>
        /// <param name="duration">动画持续时间</param>
        private System.Collections.IEnumerator SmoothMoveToPosition(Vector2 targetPos, float duration = 0.5f)
        {
            isAnimating = true;

            // 获取当前位置作为起点
            Vector2 startPos = mianju.transform.localPosition;
            float elapsedTime = 0f;

            // 平滑移动到目标位置
            while (elapsedTime < duration)
            {
                // 使用Lerp实现平滑过渡
                Vector2 currentPos = Vector2.Lerp(startPos, targetPos, elapsedTime / duration);
                mianju.transform.localPosition = currentPos;

                elapsedTime += Time.deltaTime;
                yield return null;
            }

            // 确保最终位置准确
            mianju.transform.localPosition = targetPos;
            isAnimating = false;
        }

        void OnEnable()
        {
            EventCenter.Instance.AddEventListener<int>(E_EventType.E_UpdateGameUI, UpdateValue);
        }

        void OnDisable()
        {
            EventCenter.Instance.RemoveEventListener<int>(E_EventType.E_UpdateGameUI, UpdateValue);
        }
    }
}