/*----------------------------------
 *Title:UI自动化组件生成代码生成工具
 *Date:2026/1/24 12:54:26
 *Description:变量需要以[Text]括号加组件类型的格式进行声明,然后右键窗口物体——一键生成UI数据组件脚本即可
 *注意:自动生成的内容仅追加/移除，不会覆盖手写逻辑；新增/删除组件后再次生成，会标记对应代码行
----------------------------------*/
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.UI;
using TMPro;

namespace KNXL.AutoGenerated.UI
{

	public class TestPanel : BasePanel
	{
		//字段声明
		public Button btn1;
		public Button btn2;
		public Button btn3;
		public Button btn4;
		public Button btn5;
		public Button btn6;
		public Button btn7;
		// 留给新增的字段
		public Button btn8;
		//自己手写的字段声明，不会被覆盖

		//重写Awake方法
		protected override void Awake()
		{
			base.Awake();
			//自己手写的Awake逻辑，不会被覆盖
		}

		//重写Start方法,完成事件绑定
		protected override void Start()
		{
			base.Start();
			//组件事件绑定
			btn1.onClick.AddListener(() => Onbtn1ButtonClick());
			btn2.onClick.AddListener(() => Onbtn2ButtonClick());
			btn3.onClick.AddListener(() => Onbtn3ButtonClick());
			btn4.onClick.AddListener(() => Onbtn4ButtonClick());
			btn5.onClick.AddListener(() => Onbtn5ButtonClick());
			btn6.onClick.AddListener(() => Onbtn6ButtonClick());
			btn7.onClick.AddListener(() => Onbtn7ButtonClick());
			// 留给新增的组件事件绑定
			btn8.onClick.AddListener(()=>Onbtn8ButtonClick());
			//自己手写的Start逻辑，不会被覆盖
		}

		public override void ShowMe(UnityAction callback = null)
		{
			//执行父类的ShowMe方法
			base.ShowMe(callback);
			//自己手写的ShowMe逻辑，不会被覆盖
		}

		public override void HideMe(UnityAction callback = null)
		{
			//执行父类的HideMe方法
			base.HideMe(callback);
			//自己手写的HideMe逻辑，不会被覆盖
		}

		private void Onbtn1ButtonClick()
		{
			UIMgr.Instance.ShowPanel<PopupPanel>(showAnimType: E_ShowAnimType.SlideInFromBottom);
		}

		private void Onbtn2ButtonClick()
		{
			UIMgr.Instance.ShowPanel<PopupPanel>(showAnimType: E_ShowAnimType.SlideInFromTop);
		}

		private void Onbtn3ButtonClick()
		{
			UIMgr.Instance.ShowPanel<PopupPanel>(showAnimType: E_ShowAnimType.SlideInFromLeft);
		}

		private void Onbtn4ButtonClick()
		{
			UIMgr.Instance.ShowPanel<PopupPanel>(showAnimType: E_ShowAnimType.SlideInFromRight);
		}

		private void Onbtn5ButtonClick()
		{
			UIMgr.Instance.ShowPanel<PopupPanel>(showAnimType: E_ShowAnimType.FadeIn);
		}

		private void Onbtn6ButtonClick()
		{
			UIMgr.Instance.ShowPanel<PopupPanel>(showAnimType: E_ShowAnimType.ScaleIn);
		}

		private void Onbtn7ButtonClick()
		{
			UIMgr.Instance.ShowPanel<PopupPanel>(showAnimType: E_ShowAnimType.BounceIn);
		}

		// 留给新增的组件事件绑定函数
		private void Onbtn8ButtonClick()
		{
			UIMgr.Instance.ShowPanel<PopupPanel>(showAnimType: E_ShowAnimType.None);
		}
		//自己写的内容
	}
}