using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;
using UnityEngine.Rendering.Universal;

public class CameraController
{
    private Camera mainCamera;

    public CameraController()
    {
        mainCamera = Camera.main;
    }

    /// <summary>
    /// 根据表里世界设置摄像机的cullingMask
    /// </summary>
    /// <param name="world"></param>
    public void ChangeCamProp(E_World world)
    {
        switch (world)
        {
            case E_World.In_World:
                
                // AddOverlayCam(UIMgr.Instance.UiCamera);
                break;
            case E_World.Out_World:
                
                break;
        }
    }

    public void AddOverlayCam(Camera ui)
    {
        var data = mainCamera.GetUniversalAdditionalCameraData();
        if(data.cameraStack.Contains(ui))
        {
            return;
        }
        var uiData = ui.GetUniversalAdditionalCameraData();
        if(uiData.renderType != CameraRenderType.Overlay)
        {
            uiData.renderType = CameraRenderType.Overlay;
        }
        data.cameraStack.Add(ui);
    }

    
}
