using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class CameraController
{
    private Camera mainCamera;

    public CameraController()
    {
        mainCamera = Camera.main;
    }

    /// <summary>
    /// 根据表里世界设置摄像机的cullingMask
    /// </summary>
    /// <param name="world"></param>
    public void ChangeCamProp(E_World world)
    {
        switch (world)
        {
            case E_World.In_World:
                mainCamera.backgroundColor = Color.gray;
                Debug.Log($"ChangeCamProp: 背景变成灰色");
                break;
            case E_World.Out_World:
                mainCamera.backgroundColor = Color.black;
                Debug.Log($"ChangeCamProp: 背景变成黑色");
                break;
        }
    }

    
}
