using System;
using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using KNXL.AutoGenerated.UI;
using UnityEngine;

public class DrawLine : MonoBehaviour
{
    public LineRenderer lineRenderer;
    public Player player;
    [Tooltip("线的开始宽度")]
    [SerializeField] private float startWidth = 0.05f;
    [Tooltip("线的结束宽度")]
    [SerializeField] private float endWidth = 0.1f;
    [Tooltip("左边界")]
    [SerializeField] private float leftX = -10f;
    [Tooltip("右边界")]
    [SerializeField] private float rightX = 10f;
    [Tooltip("下边界")]
    [SerializeField] private float bottomY = -5f;
    [Tooltip("上边界")]
    [SerializeField] private float topY = 5f;
    private bool enableDraw = false;
    private Vector2 lastMousePos;

    void Update()
    {
        if (enableDraw)
        {
            DrawInfoLine(this.transform.position);
        }

    }

    void OnEnable()
    {
        EventCenter.Instance.AddEventListener<E_World>(E_EventType.E_WorldChange, OnWorldChange);
    }


    void OnDisable()
    {
        EventCenter.Instance.RemoveEventListener<E_World>(E_EventType.E_WorldChange, OnWorldChange);
    }

    private void DrawInfoLine(Vector3 startPos)
    {
        Vector2 mousePos = Camera.main.ScreenToWorldPoint(Input.mousePosition);
        mousePos = HandleMousePos(mousePos);
        lastMousePos = mousePos;
        lineRenderer.SetPosition(0, startPos);
        lineRenderer.SetPosition(1, mousePos);
        lineRenderer.startWidth = startWidth;
        lineRenderer.endWidth = endWidth;
        // 指向了自己
        if (GameManager.Instance.MapCell.CalGridDisByWorldPos(startPos, mousePos) <= 10 - player.NowCrazyValue)
        {
            lineRenderer.startColor = Color.green;
            lineRenderer.endColor = Color.green;
            Cell targetCell = GameManager.Instance.MapCell.WorldToCell(mousePos);
            if (targetCell.Action != null)
            {
                lineRenderer.endColor = Color.yellow;
            }
        }
        else
        {
            lineRenderer.startColor = Color.red;
            lineRenderer.endColor = Color.red;
        }
    }

    private Vector2 HandleMousePos(Vector2 mousePos)
    {
        if (mousePos.x < leftX)
        {
            mousePos.x = leftX;
        }
        else if (mousePos.x > rightX)
        {
            mousePos.x = rightX;
        }
        if (mousePos.y < bottomY)
        {
            mousePos.y = bottomY;
        }
        else if (mousePos.y > topY)
        {
            mousePos.y = topY;
        }
        return mousePos;
    }

    public void EnableDraw()
    {
        enableDraw = true;
    }

    public void DisableDraw()
    {
        enableDraw = false;
    }

    private void ClearInfoLine()
    {
        lineRenderer.startWidth = 0f;
        lineRenderer.endWidth = 0f;
    }

    /// <summary>
    /// 当世界切换时触发的事件
    /// </summary>
    /// <param name="arg0"></param>
    private void OnWorldChange(E_World world)
    {
        switch (world)
        {
            case E_World.In_World:
                EnableDraw();
                break;
            case E_World.Out_World:
                DisableDraw();
                ClearInfoLine();
                // 判断上次指向的位置是否有交互物体
                Cell targetCell = GameManager.Instance.MapCell.WorldToCell(lastMousePos);
                // 记录一下玩家当前的位置，后面会用到这个值进行计算
                Vector3 playerPos = player.transform.position;
                int AddCrazyValue = GameManager.Instance.MapCell.CalGridDisByWorldPos(playerPos, lastMousePos);
                
                // 检查是否超出了最大范围
                bool isGameOver = false;
                if(targetCell.Action != null && AddCrazyValue > 10-player.NowCrazyValue)
                {
                    UIMgr.Instance.ShowPanel<GameOverPanel>();
                    isGameOver = true;
                }
                
                // 只有在没有游戏结束时才进行附身操作
                if (!isGameOver && targetCell.Action != null && !targetCell.Action.data.isDecorator)
                {
                    // 检查是否点击的是自己当前控制的实体
                    bool isSelfControl = false;
                    if (player.CurrentControlledAction != null)
                    {
                        // 检查目标Action是否就是当前控制的Action
                        isSelfControl = (targetCell.Action == player.CurrentControlledAction);
                    }
                    
                    // 开启附身功能
                    player.EnableControl(targetCell.Action);
                    targetCell.Action.ControlMe();
                    
                    // 只有当不是点击自己且移动距离超过0.1时才计算疯狂值
                    float distance = Vector2.Distance(playerPos, lastMousePos);
                    if (!isSelfControl && distance > 0.1f)
                    {
                        int minusCrazyValue = Mathf.CeilToInt(distance);
                        Debug.Log($"AddCrazyValue: {AddCrazyValue}, minusCrazyValue: {minusCrazyValue}");
                        player.ChangeCrazyValue(AddCrazyValue - minusCrazyValue);
                    }
                    else if (isSelfControl)
                    {
                        Debug.Log("点击自己当前控制的实体，不改变疯狂值");
                    }
                    else
                    {
                        Debug.Log("没有移动，不改变疯狂值");
                    }
                }
                break;
        }
    }

}
