using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class Mask : MonoBehaviour, IAbility
{
    public int abilityID = 10001;
    public CfgMaskData abilityData;


    void Update()
    {
        
    }

    public IAbility GetAbility()
    {
        return this;
    }

    public void InitAbility()
    {
        abilityData = AbilityManager.Instance.GetAbilityData(abilityID);
    }

    public int GetAbilityID()
    {
        return abilityID;
    }

}
