using System;
using KNXL;
using KNXL.AutoGenerated.Data;
using KNXL.AutoGenerated.UI;
using UnityEngine;

public class Player : MonoBehaviour
{
    [SerializeField] private int nowCrazyValue = 5;
    [SerializeField] private SpriteRenderer spriteRenderer;
    [SerializeField] private SpriteRenderer soulSR;
    /// <summary>
    /// 玩家持有的面具数据，宿主
    /// </summary>
    private CfgMaskData selfMaskData;
    /// <summary>
    /// 是否控制着其他面具，一开始是控制着自己的
    /// </summary>
    private bool isControl = false;
    /// <summary>
    /// 当前控制的实体
    /// </summary>
    private BaseAction currentControlledAction = null;
    
    public BaseAction CurrentControlledAction { get => currentControlledAction; }

    public int NowCrazyValue { get => nowCrazyValue; }

    private void Start()
    {
        Init();
    }

    public void Init()
    {
        selfMaskData = ConfigManager.Instance.GetData<CfgMaskData>(10007);
        ResLoadMgr.Instance.LoadRes<Sprite>(selfMaskData.resIdNoMask, (sprite) =>
        {
            spriteRenderer.sprite = sprite;
        });
        nowCrazyValue = selfMaskData.startCrazy;
        this.transform.position = new Vector3(-7, -1, 0);
        // 初始化时，释放控制，确保自己是被控制的
        ReleaseControl();
        EventCenter.Instance.EventTrigger<int>(E_EventType.E_UpdateGameUI, nowCrazyValue);
    }

    void OnEnable()
    {
        EventCenter.Instance.AddEventListener<E_World>(E_EventType.E_WorldChange, ShowSelfSoul);
    }

    void OnDisable()
    {
        EventCenter.Instance.RemoveEventListener<E_World>(E_EventType.E_WorldChange, ShowSelfSoul);
    }

    private void ShowSelfSoul(E_World curWorld)
    {
        switch (curWorld)
        {
            case E_World.In_World:
                // 如果控制着其他的面具，不显示自己原本的模样
                if(isControl)
                {
                    spriteRenderer.sprite = null;
                    break;
                }
                ResLoadMgr.Instance.LoadRes<Sprite>(selfMaskData.resSoul, (sprite) =>
                {
                    Debug.Log("加载灵魂成功" + selfMaskData.resSoul);
                    soulSR.sprite = sprite;
                });
                break;
            case E_World.Out_World:
                // 如果控制着其他的面具，不显示自己原本的模样
                if(isControl)
                {
                    spriteRenderer.sprite = null;
                    break;
                }
                soulSR.sprite = null;
                break;
        }
    }

    public void ChangeCrazyValue(int changeValue)
    {
        nowCrazyValue += changeValue;
        nowCrazyValue = Mathf.Clamp(nowCrazyValue, 0, 10);
        EventCenter.Instance.EventTrigger<int>(E_EventType.E_UpdateGameUI, nowCrazyValue);
        
        // 检查是否达到疯狂值边界，触发游戏结束
        if (nowCrazyValue == 0 || nowCrazyValue == 10)
        {
            Debug.Log($"疯狂值达到{nowCrazyValue}，游戏结束！");
            UIMgr.Instance.ShowPanel<GameOverPanel>();
        }
    }
    /// <summary>
    /// 开启控制其他面具的功能,得到主要是为了管理自己的显示
    /// </summary> <summary>
    public void EnableControl(BaseAction action)
    {
        if(action == null)
        {
            Debug.LogError("开启控制其他面具的功能时，传入的action为空");
            return;
        }
        
        // 先释放之前控制的实体
        if(currentControlledAction != null)
        {
            currentControlledAction.NotControlMe();
        }
        
        // 设置新控制的实体
        currentControlledAction = action;
        isControl = true;
        ShowSelfSoul(GameManager.Instance.CurrentWorldType);
        transform.position = action.transform.position;
    }
    
    /// <summary>
    /// 释放控制的实体
    /// </summary>
    public void ReleaseControl()
    {
        if(currentControlledAction != null)
        {
            currentControlledAction.NotControlMe();
            currentControlledAction = null;
        }
        isControl = false;
        ShowSelfSoul(GameManager.Instance.CurrentWorldType);
    }
}