using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using KNXL.AutoGenerated.UI;
using UnityEngine;

public class TestUI : MonoBehaviour
{
    void Start()
    {
        ConfigManager.Instance.Init();
        ResConfigManager.Instance.Init();
        UIMgr.Instance.ShowPanel<TestPanel>();
    }
}
