using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.UI;
using UnityEngine;

public class TestUI : MonoBehaviour
{
    void Start()
    {
        UIMgr.Instance.ShowPanel<TestPanel>();
    }
}
