using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEditor;
using UnityEngine;
using UnityEngine.Tilemaps;

public class EditorMapCell : MonoBehaviour
{
    public Vector3Int startPos; // (0,0)
    public Vector3Int endPos; // (2,2)
    public List<Tilemap> groundTiles;
    public Tile ballTile;
    public Tile mouseTile;
    public Tile wolfTile;
    public Tile chocolateTile;
    public Tile crowTile;
    public Tile elephantTile;
    public Tile rockTile;
    public Tile cassetteTile;
    public Tile streetlightTile;
    public Tile crocodileTile;
    public Tile fenceTile;
    public Tile humanTile;
    public Cell[,] cells; // 改为二维数组
    public bool showDebug = false;

    void Awake()
    {
        // 暂时移除刷新边界的调用
    }
    
    /// <summary>
    /// 刷新Tilemap边界
    /// </summary>
    // [ContextMenu("刷新Tilemap边界")]
    // public void RefreshTilemapBounds()
    // {
    //     if (ground != null)
    //     {
    //         // 强制更新Tilemap的边界
    //         ground.CompressBounds();
            
    //         // 获取更新后的边界
    //         startPos = ground.cellBounds.min;
    //         endPos = ground.cellBounds.max;
            
    //         // 验证边界是否正确
    //         BoundsInt bounds = ground.cellBounds;
    //         Debug.Log($"Tilemap边界信息: min={bounds.min}, max={bounds.max}, size={bounds.size}");
            
    //         // 初始化Cell
    //         InitCell();
    //         Debug.Log($"Tilemap边界已刷新: startPos={startPos}, endPos={endPos}");
    //     }
    //     else
    //     {
    //         Debug.LogError("RefreshTilemapBounds: ground is null");
    //     }
    // }

    void InitCell()
    {
        int cellWidth = (int)(endPos.x - startPos.x);
        int cellHeight = (int)(endPos.y - startPos.y);

        // 初始化二维数组
        cells = new Cell[cellWidth, cellHeight];

        for (int i = 0; i < cellWidth; i++)
        {
            for (int j = 0; j < cellHeight; j++)
            {
                cells[i, j] = new Cell(i, j); // 直接在二维数组中创建Cell
            }
        }
    }

    /// <summary>
    /// 通过世界坐标获取单元格
    /// </summary>
    /// <param name="worldPos"></param>
    /// <returns></returns>
    public Cell WorldToCell(Vector2 worldPos)
    {
        int cellWidth = (int)(endPos.x - startPos.x);
        int cellHeight = (int)(endPos.y - startPos.y);
        int x = (int)(worldPos.x - startPos.x);
        int y = (int)(worldPos.y - startPos.y);

        if (x >= 0 && x < cellWidth && y >= 0 && y < cellHeight)
        {
            return cells[x, y]; // 直接通过二维数组索引访问
        }
        else
        {
            return null;
        }
    }

    /// <summary>
    /// 通过单元格获取世界坐标
    /// </summary>
    /// <param name="cell"></param>
    /// <returns></returns>
    public Vector2 CellToWorld(Cell cell)
    {
        return new Vector2(startPos.x + cell.x, startPos.y + cell.y);
    }

    public Vector2 CellToWorldCenter(Cell cell)
    {
        return new Vector2(startPos.x + cell.x + 0.5f, startPos.y + cell.y + 0.5f);
    }

    public int CalGridDisByWorldPos(Vector2 worldPos1, Vector2 worldPos2)
    {
        Cell cell1 = WorldToCell(worldPos1);
        Cell cell2 = WorldToCell(worldPos2);

        if (cell1 != null && cell2 != null)
        {
            int x = Mathf.Abs(cell1.x - cell2.x);
            int y = Mathf.Abs(cell1.y - cell2.y);
            return x + y;
        }
        else
        {
            Debug.LogError("CalGridDisByWorldPos: cell1 or cell2 is null");
            return int.MaxValue;
        }
    }

#if UNITY_EDITOR
    /// <summary>
    /// 在编辑器中绘制格子的可视化效果
    /// </summary>
    void OnDrawGizmos()
    {
        if (!showDebug)
        {
            return;
        }

        // 如果格子数组未初始化，尝试初始化（仅在编辑器模式下）
        if (cells == null)
        {
            InitCell();
        }

        // 设置绘制颜色
        Gizmos.color = Color.green;

        // 获取数组尺寸
        int cellWidth = cells.GetLength(0);
        int cellHeight = cells.GetLength(1);

        // 绘制每个格子
        for (int i = 0; i < cellWidth; i++)
        {
            for (int j = 0; j < cellHeight; j++)
            {
                Cell cell = cells[i, j];
                if (cell == null) continue;

                // 获取格子的世界坐标
                Vector2 cellWorldPos = CellToWorld(cell);

                // 计算格子的四个角
                Vector3 bottomLeft = new Vector3(cellWorldPos.x, cellWorldPos.y, 0);
                Vector3 bottomRight = new Vector3(cellWorldPos.x + 1, cellWorldPos.y, 0);
                Vector3 topLeft = new Vector3(cellWorldPos.x, cellWorldPos.y + 1, 0);
                Vector3 topRight = new Vector3(cellWorldPos.x + 1, cellWorldPos.y + 1, 0);

                // 绘制格子边框
                Gizmos.DrawLine(bottomLeft, bottomRight);
                Gizmos.DrawLine(bottomRight, topRight);
                Gizmos.DrawLine(topRight, topLeft);
                Gizmos.DrawLine(topLeft, bottomLeft);

                // 在格子中心显示坐标
                GUIStyle style = new GUIStyle();
                style.normal.textColor = Color.white;
                style.fontSize = 12;
                style.alignment = TextAnchor.MiddleCenter;

                Vector3 labelPos = new Vector3(cellWorldPos.x + 0.5f, cellWorldPos.y + 0.5f, -1);
                Handles.Label(labelPos, $"({cell.x},{cell.y})", style);
            }
        }

        // 绘制整个地图的边界
        Gizmos.color = Color.red;
        Vector3 mapBottomLeft = new Vector3(startPos.x, startPos.y, 0);
        Vector3 mapBottomRight = new Vector3(endPos.x, startPos.y, 0);
        Vector3 mapTopLeft = new Vector3(startPos.x, endPos.y, 0);
        Vector3 mapTopRight = new Vector3(endPos.x, endPos.y, 0);

        Gizmos.DrawLine(mapBottomLeft, mapBottomRight);
        Gizmos.DrawLine(mapBottomRight, mapTopRight);
        Gizmos.DrawLine(mapTopRight, mapTopLeft);
        Gizmos.DrawLine(mapTopLeft, mapBottomLeft);
    }
#endif
    
    /// <summary>
    /// 生成关卡配置JSON文件（追加模式）
    /// </summary>
    [ContextMenu("生成关卡配置JSON")]
    public void GenerateLevelConfig()
    {
        if (groundTiles != null && groundTiles.Count > 0)
        {
            List<LevelConfigItem> newConfigItems = new List<LevelConfigItem>();
            
            // 遍历所有Tilemap
            foreach (Tilemap ground in groundTiles)
            {
                if (ground != null)
                {
                    // 遍历所有Tile
                    BoundsInt bounds = ground.cellBounds;
                    for (int x = bounds.min.x; x < bounds.max.x; x++)
                    {
                        for (int y = bounds.min.y; y < bounds.max.y; y++)
                        {
                            Vector3Int cellPos = new Vector3Int(x, y, 0);
                            TileBase tile = ground.GetTile(cellPos);
                            
                            if (tile != null)
                            {
                                LevelConfigItem item = new LevelConfigItem();
                                item.x = x;
                                item.y = y;
                                
                                // 根据Tile类型设置maskID和des
                                if (tile == ballTile)
                                {
                                    item.maskID = GetMaskIdByName("Ball");
                                    item.des = "Ball";
                                }
                                else if (tile == mouseTile)
                                {
                                    item.maskID = GetMaskIdByName("Mouse");
                                    item.des = "Mouse";
                                }
                                else if (tile == wolfTile)
                                {
                                    item.maskID = GetMaskIdByName("Wolf");
                                    item.des = "Wolf";
                                }
                                else if (tile == chocolateTile)
                                {
                                    item.maskID = GetMaskIdByName("Chocolate");
                                    item.des = "Chocolate";
                                }
                                else if (tile == crowTile)
                                {
                                    item.maskID = GetMaskIdByName("Crow");
                                    item.des = "Crow";
                                }
                                else if (tile == elephantTile)
                                {
                                    item.maskID = GetMaskIdByName("Elephant");
                                    item.des = "Elephant";
                                }
                                else if (tile == rockTile)
                                {
                                    item.maskID = GetMaskIdByName("Rock");
                                    item.des = "Rock";
                                }
                                else if (tile == cassetteTile)
                                {
                                    item.maskID = GetMaskIdByName("Cassette");
                                    item.des = "Cassette";
                                }
                                else if (tile == streetlightTile)
                                {
                                    item.maskID = GetMaskIdByName("Streetlight");
                                    item.des = "Streetlight";
                                }
                                else if (tile == crocodileTile)
                                {
                                    item.maskID = GetMaskIdByName("Crocodile");
                                    item.des = "Crocodile";
                                }
                                else if (tile == humanTile)
                                {
                                    item.maskID = GetMaskIdByName("Human");
                                    item.des = "Human";
                                }
                                else if (tile == fenceTile)
                                {
                                    item.maskID = GetMaskIdByName("Fence");
                                    item.des = "Fence";
                                }

                                if (item.maskID > 0)
                                {
                                    newConfigItems.Add(item);
                                }
                            }
                        }
                    }
                }
            }
            
            // 加载现有配置（如果存在）
            LevelConfig existingConfig = null;
            string path = Application.dataPath + "/Config/level_config.json";
            
            if (System.IO.File.Exists(path))
            {
                string existingJson = System.IO.File.ReadAllText(path);
                existingConfig = JsonUtility.FromJson<LevelConfig>(existingJson);
                if (existingConfig == null)
                {
                    existingConfig = new LevelConfig { items = new List<LevelConfigItem>() };
                }
            }
            else
            {
                existingConfig = new LevelConfig { items = new List<LevelConfigItem>() };
            }
            
            // 追加新配置
            existingConfig.items.AddRange(newConfigItems);
            
            // 生成JSON
            string json = JsonUtility.ToJson(existingConfig, true);
            
            // 确保目录存在
            System.IO.Directory.CreateDirectory(System.IO.Path.GetDirectoryName(path));
            
            // 保存文件
            System.IO.File.WriteAllText(path, json);
            
            Debug.Log($"关卡配置JSON已生成并追加，新增{newConfigItems.Count}个项目，总计{existingConfig.items.Count}个项目，保存路径: {path}");
        }
        else
        {
            Debug.LogError("GenerateLevelConfig: groundTiles is null or empty");
        }
    }
    
    /// <summary>
    /// 根据名称获取maskID
    /// </summary>
    /// <param name="name">面具名称</param>
    /// <returns>maskID</returns>
    private int GetMaskIdByName(string name)
    {
        // 这里需要根据实际的配置表来实现
        // 暂时返回模拟数据
        switch (name)
        {
            case "Ball": return 20005;
            case "Mouse": return 10001;
            case "Wolf": return 10002;
            case "Chocolate": return 20002;
            case "Crow": return 10003;
            case "Elephant": return 10005;
            case "Rock": return 20003;
            case "Cassette": return 20001;
            case "Streetlight": return 20004;
            case "Crocodile": return 10004;
            case "Human":return 20007;
            case "Swamp":return 20006;
            case "Fence": return 10006;
            case "Mask": return 10007;
            default: 
                Debug.LogError($"GetMaskIdByName: 未找到名称为{name}的面具");
            return 0;
        }
    }
    
    // 配置数据结构
    [System.Serializable]
    public class LevelConfig
    {
        public List<LevelConfigItem> items;
    }
    
    [System.Serializable]
    public class LevelConfigItem
    {
        public int x;
        public int y;
        public int maskID;
        public string des;
    }
}