using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class Main : MonoBehaviour
{
    // Start is called before the first frame update
    void Start()
    {
        GameManager.Instance.Init();
        CfgMaskData maskData = AbilityManager.Instance.GetAbilityData(10001);
        if (maskData != null)
        {
            Debug.Log($"能力ID为{maskData.id}的能力数据为{maskData}");
        }
    }
}
