using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using KNXL.AutoGenerated.UI;
using UnityEngine;

public class Main : MonoBehaviour
{
    // Start is called before the first frame update
    void Awake()
    {
        GameManager.Instance.Init();
        UIMgr.Instance.ShowPanel<GameStartPanel>();
        MusicMgr.Instance.PlayBKMusic("主界面");
    }

    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            MusicMgr.Instance.PlayBKMusic("主界面");
        }
        if (Input.GetKeyDown(KeyCode.E))
        {
            MusicMgr.Instance.PlaySound("游戏失败音效");
        }
    }
}
