using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class AbilityManager : BaseManager<AbilityManager>
{
    private AbilityManager()
    {
        
    }

    /// <summary>
    /// 根据能力ID得到能力数据
    /// </summary>
    /// <param name="abilityID"></param>
    /// <returns></returns>
    public CfgMaskData GetAbilityData(int abilityID)
    {
        return ConfigManager.Instance.GetData<CfgMaskData>(abilityID);
    }
}
