using System;
using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class GameLogic : MonoBehaviour
{
    /// <summary>
    /// 当前处于什么世界
    /// </summary>
    private E_World currentWorld;

    void Start()
    {
        currentWorld = E_World.Out_World;
        GameManager.Instance.CurrentWorldType = currentWorld;
        EventCenter.Instance.EventTrigger<E_World>(E_EventType.E_WorldChange, currentWorld);
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            ChangeWorld();
        }
    }

    private void ChangeWorld()
    {
        switch (currentWorld)
        {
            case E_World.In_World:
                currentWorld = E_World.Out_World;
                GameManager.Instance.CurrentWorldType = currentWorld;
                EventCenter.Instance.EventTrigger<E_World>(E_EventType.E_WorldChange, currentWorld);
                break;
            case E_World.Out_World:
                currentWorld = E_World.Out_World;
                GameManager.Instance.CurrentWorldType = currentWorld;
                EventCenter.Instance.EventTrigger<E_World>(E_EventType.E_WorldChange, currentWorld);
                break;

        }
    }
}
