using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;
using UnityEngine.SceneManagement;

public class GameManager : BaseManager<GameManager>
{
    private E_World currentWorldType;
    private int currentLevel = 1;
    private MapCell mapCell;

    private MapGenerate mapGenerate;
    private CameraController cameraController;
    private Player player;
    private GameLogic gameLogic;

    public bool isGameOver = false;
    public int CurrentLevel
    {
        get { return currentLevel; }
        private set
        {
            if (currentLevel != value)
            {
                currentLevel = value;
            }
        }
    }
    public E_World CurrentWorldType
    {
        get { return currentWorldType; }
        set
        {
            if (currentWorldType != value)
            {
                currentWorldType = value;
            }
        }
    }

    public MapCell MapCell
    {
        get
        {
            if (mapCell == null)
            {
                mapCell = GameObject.Find("Map").GetComponent<MapCell>();
            }
            return mapCell;
        }
        private set => mapCell = value;
    }
    public MapGenerate MapGenerate
    {
        get
        {
            if (mapGenerate == null)
            {
                mapGenerate = GameObject.Find("MapGenerate").GetComponent<MapGenerate>();
            }
            return mapGenerate;
        }
        private set => mapGenerate = value;
    }
    public Player Player
    {
        get
        {
            if (player == null)
            {
                player = GameObject.FindWithTag("Player").GetComponent<Player>();
            }
            return player;
        }
        private set => player = value;
    }

    public GameLogic GameLogic
    {
        get
        {
            if (gameLogic == null)
            {
                gameLogic = GameObject.Find("GameLogic").GetComponent<GameLogic>();
            }
            return gameLogic;
        }
        private set => gameLogic = value;
    }

    private GameManager()
    {
        ConfigManager.Instance.Init();
        ResConfigManager.Instance.Init();
        cameraController = new CameraController();
        SceneManager.sceneLoaded += (scene, mode) =>
        {
            cameraController.AddOverlayCam(UIMgr.Instance.UiCamera);
        };
    }

    public void Init()
    {

    }

    public void ClearGameSceneData()
    {
        MapCell = null;
        MapGenerate = null;
        Player = null;
    }

    /// <summary>
    /// 初始化玩家位置
    /// </summary>
    public void InitPlayer()
    {
        Player.Init();
    }

    public void GoToInWorld()
    {
        CurrentWorldType = E_World.In_World;
        cameraController.ChangeCamProp(E_World.In_World);
    }

    public void GoToOutWorld()
    {
        CurrentWorldType = E_World.Out_World;
        cameraController.ChangeCamProp(E_World.Out_World);
    }

    public void GoToNextLevel()
    {
        CurrentLevel++;
        // 重置到表世界
        GoToOutWorld();
    }

    public void RestartLevel()
    {
        CurrentLevel -= 1;
    }

    public void GoToFirstLevel()
    {
        CurrentLevel = 1;
    }

    public void SaveGame()
    {
        JsonMgr.Instance.SaveData(currentLevel, "LevelInfo");
    }

    public void LoadGame()
    {
        currentLevel = JsonMgr.Instance.LoadData<int>("LevelInfo");
    }
}
