using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;
using UnityEngine.SceneManagement;

public class GameManager : BaseManager<GameManager>
{
    private E_World currentWorldType = E_World.Out_World;
    private MapCell mapCell;

    private MapGenerate mapGenerate;
    private CameraController cameraController;
    public MyVector3 playerPos = new MyVector3(-7, -1, 0);
    private Player player;
    public E_World CurrentWorldType
    {
        get { return currentWorldType; }
        set
        {
            if (currentWorldType != value)
            {
                currentWorldType = value;
            }
        }
    }

    public MapCell MapCell
    {
        get
        {
            if (mapCell == null)
            {
                mapCell = GameObject.Find("Map").GetComponent<MapCell>();
            }
            return mapCell;
        }
        private set => mapCell = value;
    }
    public MapGenerate MapGenerate
    {
        get
        {
            if (mapGenerate == null)
            {
                mapGenerate = GameObject.Find("MapGenerate").GetComponent<MapGenerate>();
            }
            return mapGenerate;
        }
        private set => mapGenerate = value;
    }
    public Player Player
    {
        get
        {
            if (player == null)
            {
                player = GameObject.FindWithTag("Player").GetComponent<Player>();
            }
            return player;
        }
        private set => player = value;
    }

    private GameManager()
    {
        ConfigManager.Instance.Init();
        ResConfigManager.Instance.Init();
        cameraController = new CameraController();
        SceneManager.sceneLoaded += (scene, mode) =>
        {
            cameraController.AddOverlayCam(UIMgr.Instance.UiCamera);
        };
    }

    public void Init()
    {
        
    }

    public void ClearGameSceneData()
    {
        MapCell = null;
        MapGenerate = null;
        Player = null;
    }

    public void InitPos()
    {
        playerPos = new MyVector3(-7, -1, 0);
    }

    public void GoToInWorld()
    {
        CurrentWorldType = E_World.In_World;
        cameraController.ChangeCamProp(E_World.In_World);
    }

    public void GoToOutWorld()
    {
        CurrentWorldType = E_World.Out_World;
        cameraController.ChangeCamProp(E_World.Out_World);
    }

    public void SaveGame(object data)
    {
        JsonMgr.Instance.SaveData(data, "playerPos");
    }

    public void LoadGame()
    {
        playerPos = JsonMgr.Instance.LoadData<MyVector3>("playerPos");
    }
}
