using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class GameManager : BaseManager<GameManager>
{
    private E_World currentWorldType = E_World.Out_World;
    public MapCell mapCell;
    public MapGenerate mapGenerate;
    private CameraController cameraController;
    public MyVector3 playerPos = new MyVector3(-5,-1,0);
    public E_World CurrentWorldType
    {
        get { return currentWorldType; }
        set {
            if (currentWorldType != value)
            {
                currentWorldType = value;
            }
         }
    }
    private GameManager()
    {
        ConfigManager.Instance.Init();
        ResConfigManager.Instance.Init();
    }

    public void Init()
    {
        cameraController = new CameraController();
        mapCell = GameObject.Find("Map").GetComponent<MapCell>();
        mapGenerate = GameObject.Find("MapGenerate").GetComponent<MapGenerate>();
    }

    public void GoToInWorld()
    {
        CurrentWorldType = E_World.In_World;
        cameraController.ChangeCamProp(E_World.In_World);
    }

    public void GoToOutWorld()
    {
        CurrentWorldType = E_World.Out_World;
        cameraController.ChangeCamProp(E_World.Out_World);
    }

    public void SaveGame()
    {
        JsonMgr.Instance.SaveData(playerPos,"playerPos");
    }

    public void LoadGame()
    {
        playerPos = JsonMgr.Instance.LoadData<MyVector3>("playerPos");
    }
}
