using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEditor;
using UnityEngine;
using UnityEngine.Tilemaps;

public class MapCell : MonoBehaviour
{
    public Vector3Int startPos; // (0,0)
    public Vector3Int endPos; // (2,2)
    public Tilemap ground;
    public Tilemap info;
    public Tile canWalkTile;
    public Tile notWalkTile;
    public Cell[,] cells; // 改为二维数组
    public bool showDebug = false;
    // 用于BFS的队列和距离字典
    Queue<Cell> queue = new Queue<Cell>();
    Dictionary<Cell, int> distanceMap = new Dictionary<Cell, int>();

    void Awake()
    {
        RefreshTilemapBounds();
    }
    
    /// <summary>
    /// 强制刷新Tilemap边界
    /// </summary>
    [ContextMenu("刷新Tilemap边界")]
    public void RefreshTilemapBounds()
    {
        if(info != null)
        {
            info.CompressBounds();
        }
        if (ground != null)
        {
            // 强制更新Tilemap的边界
            ground.CompressBounds();
            
            // 获取更新后的边界
            startPos = ground.cellBounds.min;
            endPos = ground.cellBounds.max;
            
            // 验证边界是否正确
            BoundsInt bounds = ground.cellBounds;
            Debug.Log($"Tilemap边界信息: min={bounds.min}, max={bounds.max}, size={bounds.size}");
            
            // 初始化Cell
            InitCell();
            Debug.Log($"Tilemap边界已刷新: startPos={startPos}, endPos={endPos}");
        }
        else
        {
            Debug.LogError("RefreshTilemapBounds: ground is null");
        }
    }

    private void OnEnable() {
        EventCenter.Instance.AddEventListener<E_World>(E_EventType.E_WorldChange, ShowWalkableInfo);
    }

    private void OnDisable() {
        EventCenter.Instance.RemoveEventListener<E_World>(E_EventType.E_WorldChange, ShowWalkableInfo);
    }

    void InitCell()
    {
        int cellWidth = (int)(endPos.x - startPos.x);
        int cellHeight = (int)(endPos.y - startPos.y);

        // 初始化二维数组
        cells = new Cell[cellWidth, cellHeight];

        for (int i = 0; i < cellWidth; i++)
        {
            for (int j = 0; j < cellHeight; j++)
            {
                cells[i, j] = new Cell(i, j); // 直接在二维数组中创建Cell
            }
        }
    }

    /// <summary>
    /// 通过世界坐标获取单元格
    /// </summary>
    /// <param name="worldPos"></param>
    /// <returns></returns>
    public Cell WorldToCell(Vector2 worldPos)
    {
        int cellWidth = (int)(endPos.x - startPos.x);
        int cellHeight = (int)(endPos.y - startPos.y);
        int x = (int)(worldPos.x - startPos.x);
        int y = (int)(worldPos.y - startPos.y);

        if (x >= 0 && x < cellWidth && y >= 0 && y < cellHeight)
        {
            return cells[x, y]; // 直接通过二维数组索引访问
        }
        else
        {
            return null;
        }
    }

    /// <summary>
    /// 通过单元格获取世界坐标
    /// </summary>
    /// <param name="cell"></param>
    /// <returns></returns>
    public Vector2 CellToWorld(Cell cell)
    {
        return new Vector2(startPos.x + cell.x, startPos.y + cell.y);
    }

    public Vector2 CellToWorldCenter(Cell cell)
    {
        return new Vector2(startPos.x + cell.x + 0.5f, startPos.y + cell.y + 0.5f);
    }

    public int CalGridDisByWorldPos(Vector2 worldPos1, Vector2 worldPos2)
    {
        Cell cell1 = WorldToCell(worldPos1);
        Cell cell2 = WorldToCell(worldPos2);

        if (cell1 != null && cell2 != null)
        {
            int x = Mathf.Abs(cell1.x - cell2.x);
            int y = Mathf.Abs(cell1.y - cell2.y);
            return x + y;
        }
        else
        {
            Debug.LogError("CalGridDisByWorldPos: cell1 or cell2 is null");
            return int.MaxValue;
        }
    }

    /// <summary>
    /// 显示可以行走的区域
    /// </summary>
    public void ShowWalkableInfo(E_World world)
    {
        TilemapRenderer renderer = info.GetComponent<TilemapRenderer>();
        switch (world)
        {
            case E_World.In_World:
                renderer.enabled = true;
                break;
            case E_World.Out_World:
                renderer.enabled = false;
                break;
        }
    }

    /// <summary>
    /// 显示玩家可以移动的范围
    /// </summary>
    /// <param name="currentCell">当前单元格</param>
    /// <param name="maxDistance">最大移动距离</param>
    public void ShowWalkPath(Cell currentCell, int maxDistance)
    {
        // 清空之前的路径显示
        ClearWalkPath();
        
        if (currentCell == null || maxDistance <= 0)
            return;
        
        int cellWidth = cells.GetLength(0);
        int cellHeight = cells.GetLength(1);
        
        // 使用广度优先搜索计算可移动范围
        queue.Clear();
        distanceMap.Clear();
        
        queue.Enqueue(currentCell);
        distanceMap[currentCell] = 0;
        
        while (queue.Count > 0)
        {
            Cell cell = queue.Dequeue();
            int currentDistance = distanceMap[cell];
            
            // 如果当前距离已经达到最大值，不再继续搜索
            if (currentDistance >= maxDistance)
                continue;
            
            // 检查四个方向的相邻单元格
            CheckAndAddNeighbor(cell.x + 1, cell.y, currentDistance + 1, queue, distanceMap, cellWidth, cellHeight);
            CheckAndAddNeighbor(cell.x - 1, cell.y, currentDistance + 1, queue, distanceMap, cellWidth, cellHeight);
            CheckAndAddNeighbor(cell.x, cell.y + 1, currentDistance + 1, queue, distanceMap, cellWidth, cellHeight);
            CheckAndAddNeighbor(cell.x, cell.y - 1, currentDistance + 1, queue, distanceMap, cellWidth, cellHeight);
        }
        
        // 遍历所有在移动范围内的格子
        foreach (var kvp in distanceMap)
        {
            Cell cell = kvp.Key;
            int distance = kvp.Value;
            
            Vector3Int cellPos = new Vector3Int(cell.x + startPos.x, cell.y + startPos.y, 0);
            
            // 检查单元格是否可移动
            if (IsCellWalkable(cell))
            {
                // 可移动的格子显示绿色
                info.SetTile(cellPos, canWalkTile);
            }
            else
            {
                // 不可移动的格子显示红色
                info.SetTile(cellPos, notWalkTile);
            }
        }
    }

    /// <summary>
    /// 检查并添加相邻单元格
    /// </summary>
    private void CheckAndAddNeighbor(int x, int y, int distance, Queue<Cell> queue, Dictionary<Cell, int> distanceMap, int cellWidth, int cellHeight)
    {
        // 检查坐标是否在有效范围内
        if (x >= 0 && x < cellWidth && y >= 0 && y < cellHeight)
        {
            Cell neighborCell = cells[x, y];
            // 检查单元格是否存在且未被访问过
            if (neighborCell != null && !distanceMap.ContainsKey(neighborCell))
            {
                queue.Enqueue(neighborCell);
                distanceMap[neighborCell] = distance;
            }
        }
    }

    /// <summary>
    /// 检查单元格是否可移动
    /// </summary>
    public bool IsCellWalkable(Cell cell)
    {
        // 检查单元格是否存在
        if (cell == null)
            return false;
        
        // 检查单元格是否有不可移动的动作
        if (cell.Action != null && !cell.Action.data.canMove)
            return false;
        
        // 检查地面是否存在（通过Tilemap）
        Vector3Int cellPos = new Vector3Int(cell.x + startPos.x, cell.y + startPos.y, 0);
        return ground.HasTile(cellPos);
    }

    /// <summary>
    /// 清空移动路径显示
    /// </summary>
    public void ClearWalkPath()
    {
        info.ClearAllTiles();
    }

#if UNITY_EDITOR
    /// <summary>
    /// 在编辑器中绘制格子的可视化效果
    /// </summary>
    void OnDrawGizmos()
    {
        if (!showDebug)
        {
            return;
        }

        // 如果格子数组未初始化，尝试初始化（仅在编辑器模式下）
        if (cells == null)
        {
            InitCell();
        }

        // 设置绘制颜色
        Gizmos.color = Color.green;

        // 获取数组尺寸
        int cellWidth = cells.GetLength(0);
        int cellHeight = cells.GetLength(1);

        // 绘制每个格子
        for (int i = 0; i < cellWidth; i++)
        {
            for (int j = 0; j < cellHeight; j++)
            {
                Cell cell = cells[i, j];
                if (cell == null) continue;

                // 获取格子的世界坐标
                Vector2 cellWorldPos = CellToWorld(cell);

                // 计算格子的四个角
                Vector3 bottomLeft = new Vector3(cellWorldPos.x, cellWorldPos.y, 0);
                Vector3 bottomRight = new Vector3(cellWorldPos.x + 1, cellWorldPos.y, 0);
                Vector3 topLeft = new Vector3(cellWorldPos.x, cellWorldPos.y + 1, 0);
                Vector3 topRight = new Vector3(cellWorldPos.x + 1, cellWorldPos.y + 1, 0);

                // 绘制格子边框
                Gizmos.DrawLine(bottomLeft, bottomRight);
                Gizmos.DrawLine(bottomRight, topRight);
                Gizmos.DrawLine(topRight, topLeft);
                Gizmos.DrawLine(topLeft, bottomLeft);

                // 在格子中心显示坐标
                GUIStyle style = new GUIStyle();
                style.normal.textColor = Color.white;
                style.fontSize = 12;
                style.alignment = TextAnchor.MiddleCenter;

                Vector3 labelPos = new Vector3(cellWorldPos.x + 0.5f, cellWorldPos.y + 0.5f, -1);
                Handles.Label(labelPos, $"({cell.x},{cell.y})", style);
            }
        }

        // 绘制整个地图的边界
        Gizmos.color = Color.red;
        Vector3 mapBottomLeft = new Vector3(startPos.x, startPos.y, 0);
        Vector3 mapBottomRight = new Vector3(endPos.x, startPos.y, 0);
        Vector3 mapTopLeft = new Vector3(startPos.x, endPos.y, 0);
        Vector3 mapTopRight = new Vector3(endPos.x, endPos.y, 0);

        Gizmos.DrawLine(mapBottomLeft, mapBottomRight);
        Gizmos.DrawLine(mapBottomRight, mapTopRight);
        Gizmos.DrawLine(mapTopRight, mapTopLeft);
        Gizmos.DrawLine(mapTopLeft, mapBottomLeft);
    }
#endif
}