using System;
using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class MapGenerate : MonoBehaviour
{
    IEnumerator Start()
    {
        ConfigTable<CfgMapData> mapData = ConfigManager.Instance.GetTable<CfgMapData>();
        foreach (var item in mapData.AllData)
        {
            SpawnItem(item);
            yield return null;
        }
    }

    public void SpawnItem(CfgMapData item)
    {
        Vector2 worldPos = GameManager.Instance.MapCell.CellToWorldCenter(new Cell(item.x, item.y));
        GameObject obj = null;
        CfgMaskData maskData = ConfigManager.Instance.GetTable<CfgMaskData>().GetData(item.maskID);
        ResLoadMgr.Instance.LoadRes<GameObject>(maskData.resPrefab, (p) =>
        {
            GameObject prefab = p;
            obj = Instantiate(prefab, new Vector3(worldPos.x, worldPos.y, 0), Quaternion.identity);
            BaseAction maskObj = obj.GetComponent<BaseAction>();
            maskObj.Init(maskData);

            if (maskObj != null)
            {
                ResLoadMgr.Instance.LoadRes<Sprite>(maskData.resPrefab, (sp) =>
                {
                    maskObj.spriteRenderer.sprite = sp;
                    Cell targetCell = GameManager.Instance.MapCell.WorldToCell(worldPos);
                    maskObj.nowCell = targetCell;
                    targetCell.Action = maskObj;
                });
            }
        });

    }

    public void SpawnItem(CfgMaskData maskData, Vector2 worldPos)
    {
        GameObject obj = null;
        ResLoadMgr.Instance.LoadRes<GameObject>(maskData.des, (p) =>
        {
            GameObject prefab = p;
            obj = Instantiate(prefab, new Vector3(worldPos.x, worldPos.y, 0), Quaternion.identity);
            // Mask maskObj = obj.GetComponent<Mask>();
            // maskObj.abilityData = maskData;
            // maskObj.abilityID = maskData.id;

            // if (maskObj != null)
            // {
            //     ResLoadMgr.Instance.LoadRes<Sprite>(maskData.resPrefab, (sp) =>
            //     {
            //         maskObj.spriteRenderer.sprite = sp;
            //         Cell targetCell = GameManager.Instance.MapCell.WorldToCell(worldPos);
            //         maskObj.nowCell = targetCell;
            //         targetCell.SetAbility(maskObj);
            //     });
            // }
        });
    }

}
