using System;
using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class MapGenerate : MonoBehaviour
{
    /// <summary>
    /// 生成指定关卡
    /// </summary>
    /// <param name="levelID">关卡ID</param>
    public IEnumerator GenerateLevel(int levelID)
    {
        ConfigTable<CfgMapData> mapData = ConfigManager.Instance.GetTable<CfgMapData>();
        
        // 清空当前场景中的所有BaseAction对象
        BaseAction[] existingActions = GameObject.FindObjectsOfType<BaseAction>();
        foreach (var action in existingActions)
        {
            DestroyImmediate(action.gameObject);
        }
        
        // 等待销毁完成
        yield return new WaitForSeconds(0.1f);
        
        // 生成指定关卡的所有物品
        foreach (var item in mapData.AllData)
        {
            if (item.LevelID == levelID)
            {
                SpawnItem(item);
                yield return null;
            }
        }
        
        // 等待所有实体生成完成后，初始化actions列表
        yield return new WaitForSeconds(0.5f);
        GameManager.Instance.GameLogic.InitActions();
        
        Debug.Log($"关卡 {levelID} 生成完成");
    }

    public void SpawnItem(CfgMapData item)
    {
        Vector2 worldPos = new Vector2(item.x+0.5f, item.y+0.5f);
        GameObject obj = null;
        CfgMaskData maskData = ConfigManager.Instance.GetTable<CfgMaskData>().GetData(item.maskID);
        ResLoadMgr.Instance.LoadRes<GameObject>(maskData.resPrefab, (p) =>
        {
            GameObject prefab = p;
            obj = Instantiate(prefab, new Vector3(worldPos.x, worldPos.y, 0), Quaternion.identity);
            BaseAction maskObj = obj.GetComponent<BaseAction>();
            maskObj.Init(maskData);

            if (maskObj != null)
            {
                Cell targetCell = GameManager.Instance.MapCell.WorldToCell(worldPos);
                maskObj.nowCell = targetCell;
                targetCell.Action = maskObj;
            }
        });

    }

}
