using System;
using System.Collections;
using System.Collections.Generic;
using KNXL.AutoGenerated.Data;
using UnityEngine;

public class MapGenerate : MonoBehaviour
{
    public GameObject prefab1x1;
    public GameObject prefab2x2;
    public GameObject prefab2x1;

    void Start()
    {
        ConfigTable<CfgMapData> mapData = ConfigManager.Instance.GetTable<CfgMapData>();
        foreach (var item in mapData.AllData)
        {
            SpawnItem(item);
        }
    }

    private void SpawnItem(CfgMapData item)
    {
        Vector2 worldPos = GameManager.Instance.mapCell.CellToWorldCenter(new Cell(item.x, item.y));
        Debug.Log($"WorldPos: {worldPos}");
        GameObject obj = null;
        switch (item.sizeType)
        {
            case E_Volume.Size1x1:
                obj = Instantiate(prefab1x1, new Vector3(worldPos.x, worldPos.y, 0), Quaternion.identity);

                break;
            case E_Volume.Size2x2:
                obj = Instantiate(prefab2x2, new Vector3(worldPos.x, worldPos.y, 0), Quaternion.identity);
                break;
            case E_Volume.Size2x1:
                obj = Instantiate(prefab2x1, new Vector3(worldPos.x, worldPos.y, 0), Quaternion.identity);
                break;
        }
        Mask maskObj = obj.GetComponent<Mask>();
        if (maskObj != null)
        {
            Cell targetCell = new Cell(item.x, item.y);
            targetCell.SetAbility(maskObj);
        }
    }

}
