using System;
using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;

/// <summary>
/// 所有可以被附身的东西的基础行为
/// </summary>
public class BaseAction : MonoBehaviour
{
    /// <summary>
    /// 这个面具的表现
    /// </summary>
    public SpriteRenderer spriteRenderer;
    /// <summary>
    /// 处于里世界的灵魂状态显示
    /// </summary>
    public SpriteRenderer soulRenderer;
    /// <summary>
    /// 当前所处于地图的哪个格子
    /// </summary>
    public Cell nowCell;
    /// <summary>
    /// 是否处于被控制的状态
    /// </summary>
    protected bool isControl = false;
    /// <summary>
    /// 当前这种面具持有的数据
    /// </summary>
    public CfgMaskData data;
    /// <summary>
    /// 面具的理智值
    /// </summary>
    public int lizi { get; set; }
    private float xInput, yInput;
    /// <summary>
    /// 进入里世界，记录一次开始移动的位置
    /// </summary>
    private Vector3 startMovePos;
    /// <summary>
    /// 上一次移动的距离，主要是限制玩家在某个范围内移动
    /// </summary>
    private Vector3 lastMovePos;
    private Coroutine moveCoroutine;
    protected AudioSource audioSource;

    protected virtual void Start()
    {
        WorldSelfShow(GameManager.Instance.CurrentWorldType);
        if(!TryGetComponent(out audioSource))
        {
            audioSource = gameObject.AddComponent<AudioSource>();
        }
    }

    protected virtual void OnEnable()
    {
        EventCenter.Instance.AddEventListener<E_World>(E_EventType.E_WorldChange, WorldSelfShow);
    }


    protected virtual void OnDisable()
    {
        EventCenter.Instance.RemoveEventListener<E_World>(E_EventType.E_WorldChange, WorldSelfShow);
    }

    public virtual void Init(CfgMaskData cfgMaskData)
    {
        this.data = cfgMaskData;
        // 初始化理智值
        lizi = data.startLizi;
    }

    void Update()
    {
        if (isControl)
        {
            // 只有在里世界才可以移动
            if (data.canMove && GameManager.Instance.CurrentWorldType == E_World.In_World)
            {
                DoMove();
                LimitRange();
                // 同步Player位置
                SyncPlayerPosition();
            }
        }

    }

    /// <summary>
    /// 处理移动
    /// </summary>
    protected virtual void DoMove()
    {
        xInput = Input.GetAxisRaw("Horizontal");
        yInput = Input.GetAxisRaw("Vertical");
        if (xInput > 0 && this.transform.localScale == Vector3.one)
        {
            this.transform.localScale = new Vector3(-1, 1, 1);
        }
        else if (xInput < 0 && this.transform.localScale == new Vector3(-1, 1, 1))
        {
            this.transform.localScale = Vector3.one;
        }
        Vector2 moveDir = new Vector2(xInput, yInput).normalized;

        if (moveDir.magnitude > 0)
        {
            transform.Translate(moveDir * data.moveSpeed * Time.deltaTime);
        }
    }

    /// <summary>
    /// 将面具限制在某个范围内
    /// </summary>
    protected virtual void LimitRange()
    {
        // 获取当前位置
        Vector2 currentPos = transform.position;
        
        // 转换为单元格坐标
        Cell currentCell = GameManager.Instance.MapCell.WorldToCell(currentPos);
        
        // 检查当前位置是否可移动
        if (currentCell != null && !GameManager.Instance.MapCell.IsCellWalkable(currentCell))
        {
            // 如果当前位置不可移动，需要限制回可移动范围
            if (lastMovePos != Vector3.zero)
            {
                // 将位置限制回上一帧的位置
                transform.position = lastMovePos;
            }
            return;
        }
        
        // 检查是否超出了移动范围
        if (startMovePos != Vector3.zero && currentCell != null)
        {
            Cell startCell = GameManager.Instance.MapCell.WorldToCell(startMovePos);
            if (startCell != null)
            {
                // 计算当前位置到起始位置的曼哈顿距离
                int distance = Mathf.Abs(currentCell.x - startCell.x) + Mathf.Abs(currentCell.y - startCell.y);
                
                // 如果距离超过最大移动范围，限制回范围内
                if (distance > lizi)
                {
                    if (lastMovePos != Vector3.zero)
                    {
                        transform.position = lastMovePos;
                    }
                    return;
                }
            }
        }
        
        // 更新格子信息（如果格子发生了变化）
        if (currentCell != null && nowCell != currentCell)
        {
            // 清除原格子的action引用
            if (nowCell != null)
            {
                nowCell.Action = null;
            }
            
            // 更新当前格子
            nowCell = currentCell;
            
            // 设置新格子的action引用
            currentCell.Action = this;
        }
        
        // 更新上一帧的位置
        lastMovePos = transform.position;
    }

    /// <summary>
    /// 同步Player位置
    /// </summary>
    private void SyncPlayerPosition()
    {
        if (GameManager.Instance.Player != null)
        {
            GameManager.Instance.Player.transform.position = transform.position;
        }
    }

    /// <summary>
    /// 被面具控制
    /// </summary>
    public void ControlMe()
    {
        isControl = true;
        ControlShow();
        ControlShowMeWalkPath();
        // 初始化起始位置和上一帧位置
        startMovePos = transform.position;
        lastMovePos = transform.position;
        // 同步Player位置到当前实体位置
        SyncPlayerPosition();
    }

    /// <summary>
    /// 被面具脱离
    /// </summary>
    public void NotControlMe()
    {
        isControl = false;
        NotControlShow();
        GameManager.Instance.MapCell.ClearWalkPath();
        // 停止播放控制音效
        StopControlSound();
    }

    public void StopSound()
    {
        audioSource.Stop();
        audioSource.clip = null;
    }

    /// <summary>
    /// 被控制的时候自己的表现
    /// </summary>
    protected virtual void ControlShow()
    {
        ResLoadMgr.Instance.LoadRes<Sprite>(data.resIdWithMask, (sprite) =>
            {
                spriteRenderer.sprite = sprite;
            });
        // 播放移动音效
        PlayControlSound();
    }

    protected virtual void PlayControlSound()
    {
        
    }

    protected virtual void StopControlSound()
    {
        if (audioSource != null && audioSource.isPlaying)
        {
            audioSource.Stop();
        }
    }

    /// <summary>
    /// 被控制的时候，显示自己可以移动的路径
    /// </summary>
    protected virtual void ControlShowMeWalkPath()
    {
        if(data.canMove)
        {
            ShowSelfWalkPath();
        }
    }

    protected virtual void ShowSelfWalkPath()
    {
        if (data.canMove)
        {
            Debug.Log($"显示自己可以移动的路径，最大移动范围：{lizi}");
            GameManager.Instance.MapCell.ShowWalkPath(nowCell, lizi);

        }
    }

    /// <summary>
    /// 脱离控制自己的表现
    /// </summary>
    protected virtual void NotControlShow()
    {
        ResLoadMgr.Instance.LoadRes<Sprite>(data.resIdNoMask, (sprite) =>
            {
                spriteRenderer.sprite = sprite;
            });
    }

    private void WorldSelfShow(E_World curWorld)
    {
        // 如果这个东西只是一个装饰的话，那么不需要处理
        // if (data.isDecorator)
        // {
        //     return;
        // }
        switch (curWorld)
        {
            case E_World.In_World:
                // 在里世界没有被控制，就需要显示灵魂
                // 被控制了，显示的就是玩家的灵魂，这个逻辑由玩家处理
                if (!isControl)
                {
                    NotControlShow();
                    if(!data.isDecorator)
                    {
                        ResLoadMgr.Instance.LoadRes<Sprite>(data.resSoul, (sprite) =>
                        {
                            soulRenderer.sprite = sprite;
                        });
                    }
                    
                }
                else
                {
                    ControlShow();
                    DoSelfSpecial();
                    // 进入里世界时重新显示可移动范围
                    if (data.canMove)
                    {
                        ShowSelfWalkPath();
                    }
                }
                break;
            case E_World.Out_World:
                if (!isControl)
                {
                    NotControlShow();
                }
                else
                {
                    ControlShow();
                    // 从里世界切换到表世界，结算理智值
                    CalculateLizi();
                    
                }
                soulRenderer.sprite = null;
                break;
        }
    }

    protected virtual void DoSelfSpecial()
    {
        // 子类可以重写这个方法，实现自己的特殊表现
    }
    
    /// <summary>
    /// 结算理智值
    /// </summary>
    private void CalculateLizi()
    {
        if (startMovePos != Vector3.zero)
        {
            // 计算移动距离
            float distance = Vector3.Distance(startMovePos, transform.position);
            
            // 只有移动距离超过0.1时才消耗理智值
            if (distance > 1f)
            {
                // 根据移动距离消耗理智值
                // 根据移动距离消耗理智值
                int distanceCost = Mathf.CeilToInt(distance);
                lizi -= distanceCost;
                
                // 确保理智值不会小于0
                lizi = Mathf.Max(0, lizi);
                
                Debug.Log($"{data.des} 移动了 {distance:F2} 单位，消耗了 {distanceCost} 点理智值，剩余理智值: {lizi}");
                
                // 重新显示可移动范围，反映新的理智值
                if (isControl && data.canMove)
                {
                    ShowSelfWalkPath();
                }
            }
            else
            {
                Debug.Log($"{data.des} 没有移动，不消耗理智值");
            }
            
            // 重置起始位置
            startMovePos = transform.position;
        }
    }

    /// <summary>
    /// 移动到指定位置
    /// </summary>
    /// <param name="targetPos"></param>
    public void MoveTo(Vector3 targetPos)
    {
        if (moveCoroutine != null)
        {
            StopCoroutine(moveCoroutine);
        }
        moveCoroutine = StartCoroutine(MoveToCoroutine(targetPos));
    }

    private IEnumerator MoveToCoroutine(Vector3 targetPos)
    {
        // 保存原始格子
        Cell originalCell = nowCell;
        
        while (Vector3.Distance(transform.position, targetPos) > 0.01f)
        {
            // 计算移动方向
            Vector3 moveDir = (targetPos - transform.position).normalized;
            
            // 根据移动方向设置朝向
            if (moveDir.x > 0 && this.transform.localScale == Vector3.one)
            {
                // 向右移动，翻转
                this.transform.localScale = new Vector3(-1, 1, 1);
            }
            else if (moveDir.x < 0 && this.transform.localScale == new Vector3(-1, 1, 1))
            {
                // 向左移动，恢复
                this.transform.localScale = Vector3.one;
            }
            
            transform.position = Vector3.MoveTowards(transform.position, targetPos, data.moveSpeed * Time.deltaTime);
            yield return null;
        }
        
        // 移动完成后，更新格子信息
        Cell newCell = GameManager.Instance.MapCell.WorldToCell(transform.position);
        if (newCell != null)
        {
            // 清除原格子的action引用
            if (originalCell != null)
            {
                originalCell.Action = null;
            }
            
            // 更新当前格子
            nowCell = newCell;
            
            // 设置新格子的action引用
            newCell.Action = this;
        }
    }


}
