using System;
using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.Data;
using UnityEngine;

/// <summary>
/// 所有可以被附身的东西的基础行为
/// </summary>
public class BaseAction : MonoBehaviour
{
    /// <summary>
    /// 这个面具的表现
    /// </summary>
    public SpriteRenderer spriteRenderer;
    /// <summary>
    /// 处于里世界的灵魂状态显示
    /// </summary>
    public SpriteRenderer soulRenderer;
    /// <summary>
    /// 当前所处于地图的哪个格子
    /// </summary>
    public Cell nowCell;
    /// <summary>
    /// 是否处于被控制的状态
    /// </summary>
    protected bool isControl = false;
    /// <summary>
    /// 当前这种面具持有的数据
    /// </summary>
    public CfgMaskData data;
    private float xInput, yInput;
    /// <summary>
    /// 进入里世界，记录一次开始移动的位置
    /// </summary>
    private Vector3 startMovePos;
    /// <summary>
    /// 上一次移动的距离，主要是限制玩家在某个范围内移动
    /// </summary>
    private Vector3 lastMovePos;
    private Coroutine moveCoroutine;

    protected virtual void Start()
    {
        WorldSelfShow(GameManager.Instance.CurrentWorldType);
    }

    protected virtual void OnEnable()
    {
        EventCenter.Instance.AddEventListener<E_World>(E_EventType.E_WorldChange, WorldSelfShow);
    }


    protected virtual void OnDisable()
    {
        EventCenter.Instance.RemoveEventListener<E_World>(E_EventType.E_WorldChange, WorldSelfShow);
    }

    public virtual void Init(CfgMaskData cfgMaskData)
    {
        this.data = cfgMaskData;
    }

    void Update()
    {
        if (isControl)
        {
            if (data.canMove)
            {
                DoMove();
                LimitRange();
            }
        }

    }

    /// <summary>
    /// 处理移动
    /// </summary>
    protected virtual void DoMove()
    {
        xInput = Input.GetAxisRaw("Horizontal");
        yInput = Input.GetAxisRaw("Vertical");
        if (xInput > 0 && this.transform.localScale == Vector3.one)
        {
            this.transform.localScale = new Vector3(-1, 1, 1);
        }
        else if (xInput < 0 && this.transform.localScale == new Vector3(-1, 1, 1))
        {
            this.transform.localScale = Vector3.one;
        }
        Vector2 moveDir = new Vector2(xInput, yInput).normalized;

        if (moveDir.magnitude > 0)
        {
            transform.Translate(moveDir * data.moveSpeed * Time.deltaTime);
        }
    }

    /// <summary>
    /// 将面具限制在某个范围内
    /// </summary>
    protected virtual void LimitRange()
    {
        // 获取当前位置
        Vector2 currentPos = transform.position;
        
        // 转换为单元格坐标
        Cell currentCell = GameManager.Instance.MapCell.WorldToCell(currentPos);
        
        // 检查当前位置是否可移动
        if (currentCell != null && !GameManager.Instance.MapCell.IsCellWalkable(currentCell))
        {
            // 如果当前位置不可移动，需要限制回可移动范围
            if (lastMovePos != Vector3.zero)
            {
                // 将位置限制回上一帧的位置
                transform.position = lastMovePos;
            }
            return;
        }
        
        // 检查是否超出了移动范围
        if (startMovePos != Vector3.zero && currentCell != null)
        {
            Cell startCell = GameManager.Instance.MapCell.WorldToCell(startMovePos);
            if (startCell != null)
            {
                // 计算当前位置到起始位置的曼哈顿距离
                int distance = Mathf.Abs(currentCell.x - startCell.x) + Mathf.Abs(currentCell.y - startCell.y);
                
                // 如果距离超过最大移动范围，限制回范围内
                if (distance > data.startLizi)
                {
                    if (lastMovePos != Vector3.zero)
                    {
                        transform.position = lastMovePos;
                    }
                    return;
                }
            }
        }
        
        // 更新上一帧的位置
        lastMovePos = transform.position;
    }

    /// <summary>
    /// 被面具控制
    /// </summary>
    public void ControlMe()
    {
        isControl = true;
        ControlShow();
        ControlShowMeWalkPath();
        // 初始化起始位置和上一帧位置
        startMovePos = transform.position;
        lastMovePos = transform.position;
    }

    /// <summary>
    /// 被面具脱离
    /// </summary>
    public void NotControlMe()
    {
        isControl = false;
        NotControlShow();
        GameManager.Instance.MapCell.ClearWalkPath();
    }

    /// <summary>
    /// 被控制的时候自己的表现
    /// </summary>
    protected virtual void ControlShow()
    {
        ResLoadMgr.Instance.LoadRes<Sprite>(data.resIdWithMask, (sprite) =>
            {
                spriteRenderer.sprite = sprite;
            });
    }

    /// <summary>
    /// 被控制的时候，显示自己可以移动的路径
    /// </summary>
    protected virtual void ControlShowMeWalkPath()
    {
        if(data.canMove)
        {
            ShowSelfWalkPath();
        }
    }

    protected virtual void ShowSelfWalkPath()
    {
        if (data.canMove)
        {
            GameManager.Instance.MapCell.ShowWalkPath(nowCell, data.startLizi);

        }
    }

    /// <summary>
    /// 脱离控制自己的表现
    /// </summary>
    protected virtual void NotControlShow()
    {
        ResLoadMgr.Instance.LoadRes<Sprite>(data.resIdNoMask, (sprite) =>
            {
                spriteRenderer.sprite = sprite;
            });
    }

    private void WorldSelfShow(E_World curWorld)
    {
        // 如果这个东西只是一个装饰的话，那么不需要处理
        if (data.isDecorator)
        {
            return;
        }
        switch (curWorld)
        {
            case E_World.In_World:
                // 在里世界没有被控制，就需要显示灵魂
                // 被控制了，显示的就是玩家的灵魂，这个逻辑由玩家处理
                if (!isControl)
                {
                    NotControlShow();
                    ResLoadMgr.Instance.LoadRes<Sprite>(data.resSoul, (sprite) =>
                    {
                        soulRenderer.sprite = sprite;
                    });
                }
                else
                {
                    ControlShow();
                    DoSelfSpecial();
                }
                break;
            case E_World.Out_World:
                if (!isControl)
                {
                    NotControlShow();
                }
                else
                {
                    ControlShow();
                }
                soulRenderer.sprite = null;
                break;
        }
    }

    protected virtual void DoSelfSpecial()
    {
        // 子类可以重写这个方法，实现自己的特殊表现
    }

    /// <summary>
    /// 移动到指定位置
    /// </summary>
    /// <param name="targetPos"></param>
    public void MoveTo(Vector3 targetPos)
    {
        if (moveCoroutine != null)
        {
            StopCoroutine(moveCoroutine);
        }
        moveCoroutine = StartCoroutine(MoveToCoroutine(targetPos));
    }

    private IEnumerator MoveToCoroutine(Vector3 targetPos)
    {
        while (transform.position != targetPos)
        {
            transform.position = Vector3.MoveTowards(transform.position, targetPos, data.moveSpeed * Time.deltaTime);
            yield return null;
        }
    }


}
