using System.Collections;
using System.Collections.Generic;
using KNXL;
using KNXL.AutoGenerated.UI;
using UnityEngine;

/// <summary>
/// 磁带类
/// </summary>
public class Cassette : BaseAction
{
    protected override void DoSelfSpecial()
    {
        // 子类可以重写这个方法，实现自己的特殊表现
        SaveGameData();
        ResetPlayerCrazyValue();
    }
    
    /// <summary>
    /// 保存游戏数据
    /// </summary>
    private void SaveGameData()
    {
        GameManager.Instance.GoToNextLevel();
        // 设置下一关
        // 现在只有5关
        if(GameManager.Instance.CurrentLevel > 5)
        {
            UIMgr.Instance.ShowPanel<EndPanel>();
        }
        else
        {
            // 应该是显示通过面板
        }
        
        
        GameManager.Instance.SaveGame();
        
        Debug.Log($"游戏数据已保存，当前关卡: {GameManager.Instance.CurrentLevel}");
    }
    
    /// <summary>
    /// 重置玩家疯狂值
    /// </summary>
    private void ResetPlayerCrazyValue()
    {
        // 重置疯狂值为5
        int resetValue = 5 - GameManager.Instance.Player.NowCrazyValue;
        GameManager.Instance.Player.ChangeCrazyValue(resetValue);
        
        Debug.Log("玩家疯狂值已重置为5");
    }
}