using System;
using System.Collections.Generic;
using UnityEngine;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// MapData配置表（自动生成）
    /// </summary>
    [Serializable]
    public class CfgMapData : BaseConfig
    {
        /// <summary>
        /// 表的主键(1开头表示表世界，2开头表示里世界)
        /// </summary>
        [SerializeField]
        public int id { get; set; }

        /// <summary>
        /// 这个面具对应的描述
        /// </summary>
        [SerializeField]
        public string des { get; set; }

        /// <summary>
        /// 这个面具对应的体积大小
        /// </summary>
        [SerializeField]
        public E_Volume sizeType { get; set; }

        /// <summary>
        /// 生成位置对应的x坐标
        /// </summary>
        [SerializeField]
        public int x { get; set; }

        /// <summary>
        /// 生成位置对应的y坐标
        /// </summary>
        [SerializeField]
        public int y { get; set; }

        /// <summary>
        /// 对应MaskData中面具的ID
        /// </summary>
        [SerializeField]
        public int maskID { get; set; }

        /// <summary>
        /// 主键（id）
        /// </summary>
        public override object PrimaryKey => id;

    /// <summary>
    /// 数据合法性校验（适配Unity）
    /// </summary>
    public override bool Validate()
    {
        // 主键校验
        if (id <= 0)
        {
            ConfigHelper.LogError("CfgMapData", $"主键id非法：{id}");
            return false;
        }
        // 表的主键(1开头表示表世界，2开头表示里世界)范围校验
        if (id < 1)
        {
            ConfigHelper.LogError("CfgMapData", $"表的主键(1开头表示表世界，2开头表示里世界)id值{id}小于最小值1");
            return false;
        }
        if (id > 99999)
        {
            ConfigHelper.LogError("CfgMapData", $"表的主键(1开头表示表世界，2开头表示里世界)id值{id}大于最大值99999");
            return false;
        }
        return true;
    }
    }
}