using System;
using System.Collections.Generic;
using UnityEngine;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// MaskData配置表（自动生成）
    /// </summary>
    [Serializable]
    public class CfgMaskData : BaseConfig
    {
        /// <summary>
        /// 表的主键(1开头表示表世界，2开头表示里世界)
        /// </summary>
        [SerializeField]
        public int id { get; set; }

        /// <summary>
        /// 这个面具对应的描述
        /// </summary>
        [SerializeField]
        public string des { get; set; }

        /// <summary>
        /// 可以附身的面具类型
        /// </summary>
        [SerializeField]
        public E_MaskType maskType { get; set; }

        /// <summary>
        /// 面具对应的Sprite路径
        /// </summary>
        [SerializeField]
        public string spritePath { get; set; }

        /// <summary>
        /// 初始的理智值
        /// </summary>
        [SerializeField]
        public int startLizi { get; set; }

        /// <summary>
        /// 面具对应的输入方式
        /// </summary>
        [SerializeField]
        public E_InputAction inputAction { get; set; }

        /// <summary>
        /// 体积
        /// </summary>
        [SerializeField]
        public string volume { get; set; }

        /// <summary>
        /// 是否能阻挡物品
        /// </summary>
        [SerializeField]
        public bool canStopItem { get; set; }

        /// <summary>
        /// 是否能被携带
        /// </summary>
        [SerializeField]
        public bool canPickItem { get; set; }

        /// <summary>
        /// 检测范围
        /// </summary>
        [SerializeField]
        public int checkDis { get; set; }

        /// <summary>
        /// 可以吸引的类型
        /// </summary>
        [SerializeField]
        public E_MaskType loveType { get; set; }

        /// <summary>
        /// 可以驱逐的类型
        /// </summary>
        [SerializeField]
        public E_MaskType hateType { get; set; }

        /// <summary>
        /// 必须要是阻挡物品的前提下，可以通过的类型
        /// </summary>
        [SerializeField]
        public E_MaskType crossType { get; set; }

        /// <summary>
        /// 这个字段没用了，只是为了枚举的生成
        /// </summary>
        [SerializeField]
        public E_World worldType { get; set; }

        /// <summary>
        /// 主键（id）
        /// </summary>
        public override object PrimaryKey => id;

    /// <summary>
    /// 数据合法性校验（适配Unity）
    /// </summary>
    public override bool Validate()
    {
        // 主键校验
        if (id <= 0)
        {
            ConfigHelper.LogError("CfgMaskData", $"主键id非法：{id}");
            return false;
        }
        // 表的主键(1开头表示表世界，2开头表示里世界)范围校验
        if (id < 1)
        {
            ConfigHelper.LogError("CfgMaskData", $"表的主键(1开头表示表世界，2开头表示里世界)id值{id}小于最小值1");
            return false;
        }
        if (id > 99999)
        {
            ConfigHelper.LogError("CfgMaskData", $"表的主键(1开头表示表世界，2开头表示里世界)id值{id}大于最大值99999");
            return false;
        }
        return true;
    }
    }
}