using System;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 面具对应的输入方式
    /// </summary>
    [System.Serializable]
    public enum E_InputAction
    {
        /// <summary>
        /// WASD移动
        /// </summary>
        WASD = 0,
        /// <summary>
        /// 鼠标
        /// </summary>
        Mouse = 1,
        /// <summary>
        /// X轴水平移动
        /// </summary>
        X = 2,
        /// <summary>
        /// Y轴竖直移动
        /// </summary>
        Y = 3,
    }
}