using System;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 可以附身的面具类型
    /// </summary>
    [System.Serializable]
    public enum E_MaskType
    {
        /// <summary>
        /// 老鼠
        /// </summary>
        Mouse = 0,
        /// <summary>
        /// 磁带
        /// </summary>
        Cassette = 1,
        /// <summary>
        /// 狼
        /// </summary>
        Wolf = 2,
        /// <summary>
        /// 乌鸦
        /// </summary>
        Crow = 3,
        /// <summary>
        /// 鳄鱼
        /// </summary>
        Crocodile = 4,
        /// <summary>
        /// 大象
        /// </summary>
        Elephant = 5,
        /// <summary>
        /// 巧克力
        /// </summary>
        Chocolate = 6,
        /// <summary>
        /// 岩石
        /// </summary>
        Rock = 7,
        /// <summary>
        /// 路灯
        /// </summary>
        Streetlight = 8,
        /// <summary>
        /// 皮球
        /// </summary>
        Ball = 9,
        /// <summary>
        /// 沼泽
        /// </summary>
        Swamp = 10,
        /// <summary>
        /// 人
        /// </summary>
        Human = 11,
        /// <summary>
        /// 栅栏
        /// </summary>
        Fence = 12,
    }
}