using System;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 可以附身的面具类型
    /// </summary>
    [System.Serializable]
    public enum E_MaskType
    {
        /// <summary>
        /// 老鼠
        /// </summary>
        Mouse = 0,
        /// <summary>
        /// 磁带
        /// </summary>
        Cassette = 1,
    }
}