using System;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 面具对应的特殊能力
    /// </summary>
    [System.Serializable]
    public enum E_SpAbility
    {
        /// <summary>
        /// 无特殊能力
        /// </summary>
        Normal = 0,
        /// <summary>
        /// 磁带的保存
        /// </summary>
        Save = 1,
    }
}