using System;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 体积大小
    /// </summary>
    [System.Serializable]
    public enum E_Volume
    {
        /// <summary>
        /// 1x1
        /// </summary>
        Size1x1 = 0,
        /// <summary>
        /// 2x2
        /// </summary>
        Size2x2 = 1,
        /// <summary>
        /// 2x1
        /// </summary>
        Size2x1 = 2,
    }
}