using System;

namespace KNXL.AutoGenerated.Data
{
    /// <summary>
    /// 世界类型
    /// </summary>
    [System.Serializable]
    public enum E_World
    {
        /// <summary>
        /// 里世界
        /// </summary>
        In_World = 0,
        /// <summary>
        /// 表世界
        /// </summary>
        Out_World = 1,
    }
}